using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EduApi.Migrations
{
    /// <inheritdoc />
    /// <remarks>
    /// Adds the "OnlineLesson" feature: a standalone (no-Unit) container for
    /// online lectures, reachable by students only by redeeming a Code for
    /// it (see OnlineLessonsController, CodesController, StudentsController.RedeemCode).
    /// </remarks>
    public partial class AddOnlineLessons : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""OnlineLessons"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Name"" text NOT NULL,
                    ""SchoolYear"" integer NOT NULL,
                    ""ImageUrl"" text NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT now(),
                    ""TeacherId"" integer NOT NULL
                );
            ");
            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_OnlineLessons_TeacherId"" ON ""OnlineLessons"" (""TeacherId"");
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""StudentOnlineLessonUnlocks"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""TeacherId"" integer NOT NULL,
                    ""StudentId"" integer NOT NULL,
                    ""OnlineLessonId"" integer NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT now()
                );
            ");
            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_StudentOnlineLessonUnlocks_TeacherId"" ON ""StudentOnlineLessonUnlocks"" (""TeacherId"");
            ");
            migrationBuilder.Sql(@"
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_StudentOnlineLessonUnlocks_StudentId_OnlineLessonId""
                    ON ""StudentOnlineLessonUnlocks"" (""StudentId"", ""OnlineLessonId"");
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE ""Lectures""
                ADD COLUMN IF NOT EXISTS ""OnlineLessonId"" integer NULL;
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE ""Codes""
                ADD COLUMN IF NOT EXISTS ""OnlineLessonIdsCsv"" text NOT NULL DEFAULT '';
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(name: "OnlineLessonIdsCsv", table: "Codes");
            migrationBuilder.DropColumn(name: "OnlineLessonId", table: "Lectures");
            migrationBuilder.DropTable(name: "StudentOnlineLessonUnlocks");
            migrationBuilder.DropTable(name: "OnlineLessons");
        }
    }
}
