using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EduApi.Migrations
{
    /// <inheritdoc />
    /// <remarks>
    /// Adds the "External Book" feature ("الكتب الخارجية"): a Unit-shaped
    /// container (own Name/SchoolYear/Month/Image, own nested Lessons,
    /// Lectures/Materials created inside it exactly like a Unit's) with one
    /// extra optional field, UnitId -- when set, students subscribed to that
    /// Unit get the book too, with no code needed; when null, the only way in
    /// is redeeming a Code (see ExternalBooksController, CodesController,
    /// StudentsController.RedeemCode, LecturesController).
    ///
    /// Written as idempotent raw SQL, same style as AddOnlineLessons --
    /// PendingModelChangesWarning is already suppressed in Program.cs for
    /// exactly this reason (see the comment there).
    /// </remarks>
    public partial class AddExternalBooks : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""ExternalBooks"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Name"" text NOT NULL,
                    ""SchoolYear"" integer NOT NULL,
                    ""Month"" integer NULL,
                    ""ImageUrl"" text NULL,
                    ""UnitId"" integer NULL,
                    ""TeacherId"" integer NOT NULL
                );
            ");
            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_ExternalBooks_TeacherId"" ON ""ExternalBooks"" (""TeacherId"");
            ");
            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_ExternalBooks_UnitId"" ON ""ExternalBooks"" (""UnitId"");
            ");
            // SetNull on the parent Unit's deletion -- the book itself is
            // never deleted, it just falls back to being code-only.
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'FK_ExternalBooks_Units_UnitId'
                    ) THEN
                        ALTER TABLE ""ExternalBooks""
                        ADD CONSTRAINT ""FK_ExternalBooks_Units_UnitId""
                        FOREIGN KEY (""UnitId"") REFERENCES ""Units"" (""Id"") ON DELETE SET NULL;
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""ExternalBookLessons"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ExternalBookId"" integer NOT NULL,
                    ""LessonIndex"" integer NOT NULL,
                    ""Name"" text NOT NULL,
                    ""ImageUrl"" text NULL
                );
            ");
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'FK_ExternalBookLessons_ExternalBooks_ExternalBookId'
                    ) THEN
                        ALTER TABLE ""ExternalBookLessons""
                        ADD CONSTRAINT ""FK_ExternalBookLessons_ExternalBooks_ExternalBookId""
                        FOREIGN KEY (""ExternalBookId"") REFERENCES ""ExternalBooks"" (""Id"") ON DELETE CASCADE;
                    END IF;
                END $$;
            ");
            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_ExternalBookLessons_ExternalBookId"" ON ""ExternalBookLessons"" (""ExternalBookId"");
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""StudentExternalBookSubscriptions"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""TeacherId"" integer NOT NULL,
                    ""StudentId"" integer NOT NULL,
                    ""ExternalBookId"" integer NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT now()
                );
            ");
            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_StudentExternalBookSubscriptions_TeacherId"" ON ""StudentExternalBookSubscriptions"" (""TeacherId"");
            ");
            migrationBuilder.Sql(@"
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_StudentExternalBookSubscriptions_StudentId_ExternalBookId""
                    ON ""StudentExternalBookSubscriptions"" (""StudentId"", ""ExternalBookId"");
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE ""Lectures""
                ADD COLUMN IF NOT EXISTS ""ExternalBookId"" integer NULL;
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE ""Codes""
                ADD COLUMN IF NOT EXISTS ""ExternalBookIdsCsv"" text NOT NULL DEFAULT '';
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(name: "ExternalBookIdsCsv", table: "Codes");
            migrationBuilder.DropColumn(name: "ExternalBookId", table: "Lectures");
            migrationBuilder.DropTable(name: "StudentExternalBookSubscriptions");
            migrationBuilder.DropTable(name: "ExternalBookLessons");
            migrationBuilder.DropTable(name: "ExternalBooks");
        }
    }
}
